/* =====================================================================
   DataCost Architect — PRICING DATABASE (gerado)
   NÃO EDITAR À MÃO. Saída de tools/fetch_pricing.py.
   method: 'api' = API pública do fornecedor | 'curated' = tabela pública
           transcrita | 'account' = lido da própria conta.
   ===================================================================== */
const PRICING_META = {
  "generated_at": "2026-09-25",
  "generator": "tools/fetch_pricing.py v0.3",
  "aws_region": "us-east-1",
  "counts": {
    "api": 25,
    "curated": 11,
    "account": 0
  },
  "fx": {
    "USD": 1.0,
    "BRL": 5.1808,
    "EUR": 0.87974,
    "source": "Frankfurter (taxas de referência do BCE)",
    "date": "2026-09-24",
    "method": "api"
  }
};

const PRICING = [
  {
    "provider": "AWS",
    "service": "Athena",
    "region": "us-east-1",
    "sku": "data-scanned",
    "metric": "Query",
    "unit": "TB scanned",
    "price": 5.0,
    "currency": "USD",
    "valid_from": "2026-09-11",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonAthena/us-east-1 (publicado 2026-09-11)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "DMS",
    "region": "us-east-1",
    "sku": "dms.c5.large",
    "metric": "Compute",
    "unit": "instance-hour",
    "price": 0.119,
    "currency": "USD",
    "valid_from": "2026-09-11",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AWSDatabaseMigrationSvc/us-east-1 (publicado 2026-09-11)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "EC2",
    "region": "us-east-1",
    "sku": "m5.2xlarge",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.384,
    "currency": "USD",
    "valid_from": "2026-09-24",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonEC2/us-east-1 (publicado 2026-09-24)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "EC2",
    "region": "us-east-1",
    "sku": "m5.xlarge",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.192,
    "currency": "USD",
    "valid_from": "2026-09-24",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonEC2/us-east-1 (publicado 2026-09-24)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "EC2",
    "region": "us-east-1",
    "sku": "r5.xlarge",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.252,
    "currency": "USD",
    "valid_from": "2026-09-24",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonEC2/us-east-1 (publicado 2026-09-24)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "EMR",
    "region": "us-east-1",
    "sku": "emr-uplift-m5.2xlarge",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.096,
    "currency": "USD",
    "valid_from": "2026-09-11",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — ElasticMapReduce/us-east-1 (publicado 2026-09-11)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "EMR",
    "region": "us-east-1",
    "sku": "emr-uplift-m5.xlarge",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.048,
    "currency": "USD",
    "valid_from": "2026-09-11",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — ElasticMapReduce/us-east-1 (publicado 2026-09-11)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "Glue",
    "region": "us-east-1",
    "sku": "catalog-objects",
    "metric": "Metadata",
    "unit": "100k objects-month",
    "price": 1.0,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "AWS Glue Pricing (página pública)",
    "method": "curated"
  },
  {
    "provider": "AWS",
    "service": "Glue",
    "region": "us-east-1",
    "sku": "crawler-dpu",
    "metric": "Compute",
    "unit": "DPU-hour",
    "price": 0.44,
    "currency": "USD",
    "valid_from": "2026-09-11",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AWSGlue/us-east-1 (publicado 2026-09-11)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "Glue",
    "region": "us-east-1",
    "sku": "etl-dpu",
    "metric": "Compute",
    "unit": "DPU-hour",
    "price": 0.44,
    "currency": "USD",
    "valid_from": "2026-09-11",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AWSGlue/us-east-1 (publicado 2026-09-11)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "Glue",
    "region": "us-east-1",
    "sku": "etl-dpu-gen2",
    "metric": "Compute",
    "unit": "DPU-hour",
    "price": 0.308,
    "currency": "USD",
    "valid_from": "2026-09-11",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AWSGlue/us-east-1 (publicado 2026-09-11)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "Network",
    "region": "us-east-1",
    "sku": "cross-region-out",
    "metric": "Transfer",
    "unit": "GB",
    "price": 0.02,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "AWS Data Transfer Pricing (página pública)",
    "method": "curated"
  },
  {
    "provider": "AWS",
    "service": "Network",
    "region": "us-east-1",
    "sku": "internet-out",
    "metric": "Transfer",
    "unit": "GB",
    "price": 0.09,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "AWS Data Transfer Pricing (página pública)",
    "method": "curated"
  },
  {
    "provider": "AWS",
    "service": "S3",
    "region": "us-east-1",
    "sku": "get-requests",
    "metric": "Requests",
    "unit": "1k requests",
    "price": 0.0004,
    "currency": "USD",
    "valid_from": "2026-09-18",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonS3/us-east-1 (publicado 2026-09-18)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "S3",
    "region": "us-east-1",
    "sku": "glacier-ir",
    "metric": "Storage",
    "unit": "GB-month",
    "price": 0.004,
    "currency": "USD",
    "valid_from": "2026-09-18",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonS3/us-east-1 (publicado 2026-09-18)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "S3",
    "region": "us-east-1",
    "sku": "ia-storage",
    "metric": "Storage",
    "unit": "GB-month",
    "price": 0.0125,
    "currency": "USD",
    "valid_from": "2026-09-18",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonS3/us-east-1 (publicado 2026-09-18)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "S3",
    "region": "us-east-1",
    "sku": "put-requests",
    "metric": "Requests",
    "unit": "1k requests",
    "price": 0.005,
    "currency": "USD",
    "valid_from": "2026-09-18",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonS3/us-east-1 (publicado 2026-09-18)",
    "method": "api"
  },
  {
    "provider": "AWS",
    "service": "S3",
    "region": "us-east-1",
    "sku": "standard-storage",
    "metric": "Storage",
    "unit": "GB-month",
    "price": 0.023,
    "currency": "USD",
    "valid_from": "2026-09-18",
    "retrieved_at": "2026-09-25",
    "source": "AWS Price List bulk — AmazonS3/us-east-1 (publicado 2026-09-18)",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "ADLS",
    "region": "eastus",
    "sku": "ia-storage",
    "metric": "Storage",
    "unit": "GB-month",
    "price": 0.0152,
    "currency": "USD",
    "valid_from": "2019-04-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Azure Data Lake Storage Gen2 Hierarchical Namespace / Cool LRS Data Stored",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "ADLS",
    "region": "eastus",
    "sku": "read-ops",
    "metric": "Requests",
    "unit": "10k operations",
    "price": 0.0052,
    "currency": "USD",
    "valid_from": "2019-04-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Azure Data Lake Storage Gen2 Hierarchical Namespace / Hot Read Operations",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "ADLS",
    "region": "eastus",
    "sku": "standard-storage",
    "metric": "Storage",
    "unit": "GB-month",
    "price": 0.0191,
    "currency": "USD",
    "valid_from": "2019-04-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Azure Data Lake Storage Gen2 Hierarchical Namespace / Hot LRS Data Stored",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "ADLS",
    "region": "eastus",
    "sku": "write-ops",
    "metric": "Requests",
    "unit": "10k operations",
    "price": 0.065,
    "currency": "USD",
    "valid_from": "2019-04-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Azure Data Lake Storage Gen2 Hierarchical Namespace / Hot Write Operations",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "Databricks",
    "region": "eastus",
    "sku": "dbu-jobs-photon",
    "metric": "Compute",
    "unit": "DBU",
    "price": 0.3,
    "currency": "USD",
    "valid_from": "2022-11-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Azure Databricks / Premium Jobs Compute Photon DBU",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "Databricks",
    "region": "eastus",
    "sku": "dbu-jobs-premium",
    "metric": "Compute",
    "unit": "DBU",
    "price": 0.3,
    "currency": "USD",
    "valid_from": "2019-03-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Azure Databricks / Premium Jobs Compute DBU",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "Databricks",
    "region": "eastus",
    "sku": "dbu-sql-serverless",
    "metric": "Compute",
    "unit": "DBU",
    "price": 0.7,
    "currency": "USD",
    "valid_from": "2024-02-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Azure Databricks Regional / Premium Serverless SQL DBU",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "VM",
    "region": "eastus",
    "sku": "Standard_D4s_v5",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.192,
    "currency": "USD",
    "valid_from": "2021-11-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Virtual Machines Dsv5 Series / D4s v5",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "VM",
    "region": "eastus",
    "sku": "Standard_D8s_v5",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.384,
    "currency": "USD",
    "valid_from": "2021-11-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Virtual Machines Dsv5 Series / D8s v5",
    "method": "api"
  },
  {
    "provider": "Azure",
    "service": "VM",
    "region": "eastus",
    "sku": "Standard_E4s_v5",
    "metric": "Compute",
    "unit": "node-hour",
    "price": 0.252,
    "currency": "USD",
    "valid_from": "2021-11-01",
    "retrieved_at": "2026-09-25",
    "source": "Azure Retail Prices API — Virtual Machines Esv5 Series / E4s v5",
    "method": "api"
  },
  {
    "provider": "Snowflake",
    "service": "Snowpipe",
    "region": "aws-us-east-1",
    "sku": "snowpipe-credit",
    "metric": "Compute",
    "unit": "credit",
    "price": 2.0,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Snowflake Serverless Credit Table",
    "method": "curated"
  },
  {
    "provider": "Snowflake",
    "service": "Storage",
    "region": "aws-us-east-1",
    "sku": "capacity-storage",
    "metric": "Storage",
    "unit": "TB-month",
    "price": 23.0,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Snowflake Storage Pricing — capacity",
    "method": "curated"
  },
  {
    "provider": "Snowflake",
    "service": "Storage",
    "region": "aws-us-east-1",
    "sku": "ondemand-storage",
    "metric": "Storage",
    "unit": "TB-month",
    "price": 40.0,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Snowflake Storage Pricing — on demand",
    "method": "curated"
  },
  {
    "provider": "Snowflake",
    "service": "Warehouse",
    "region": "aws-us-east-1",
    "sku": "credit-enterprise",
    "metric": "Compute",
    "unit": "credit",
    "price": 3.0,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Snowflake Credit Consumption Table — Enterprise, AWS us-east-1",
    "method": "curated"
  },
  {
    "provider": "Snowflake",
    "service": "Warehouse",
    "region": "aws-us-east-1",
    "sku": "credit-standard",
    "metric": "Compute",
    "unit": "credit",
    "price": 2.0,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Snowflake Credit Consumption Table — Standard, AWS us-east-1",
    "method": "curated"
  },
  {
    "provider": "Databricks",
    "service": "Jobs Compute",
    "region": "aws-us-east-1",
    "sku": "dbu-jobs-premium",
    "metric": "Compute",
    "unit": "DBU",
    "price": 0.15,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Databricks Pricing — Jobs Compute (Premium, AWS)",
    "method": "curated"
  },
  {
    "provider": "Databricks",
    "service": "Jobs Compute",
    "region": "aws-us-east-1",
    "sku": "dbu-jobs-serverless",
    "metric": "Compute",
    "unit": "DBU",
    "price": 0.35,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Databricks Pricing — Serverless Jobs (AWS)",
    "method": "curated"
  },
  {
    "provider": "Databricks",
    "service": "SQL Warehouse",
    "region": "aws-us-east-1",
    "sku": "dbu-sql-serverless",
    "metric": "Compute",
    "unit": "DBU",
    "price": 0.7,
    "currency": "USD",
    "valid_from": "2026-09-25",
    "retrieved_at": "2026-09-25",
    "source": "Databricks Pricing — SQL Serverless (AWS)",
    "method": "curated"
  }
];

const price = (provider, service, sku) => {
  const r = PRICING.find(p => p.provider===provider && p.service===service && p.sku===sku);
  if (!r) throw new Error(`Preço não encontrado: ${provider}/${service}/${sku}`);
  return r.price;
};

/* Câmbio — camada de apresentação apenas (seção 25 do scopo.md). */
const FX = { USD:1, BRL:5.1808, EUR:0.8797 };
const FX_META = {"USD": 1.0, "BRL": 5.1808, "EUR": 0.87974, "source": "Frankfurter (taxas de referência do BCE)", "date": "2026-09-24", "method": "api"};
